<?php

/**
 * @file
 * Contains parish_school_locator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\leaflet\LeafletService;

/**
 * Implements hook_help().
 */
function parish_school_locator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the parish_school_locator module.
    case 'help.page.parish_school_locator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Find parishes and schools by address, name, and mass time') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function parish_school_locator_theme() {
  return [
    'parish_school_locator' => [
      'render element' => 'children',
    ],
  ];
}

/*function parish_school_locator_preprocess_views_view_field__field_geolocation(&$variables) {
    $lat = $variables['row']->_entity->get('field_geolocation')->getValue()[0]['lat'];
    $lng = $variables['row']->_entity->get('field_geolocation')->getValue()[0]['lng'];

    $features = [
        [
            'type' => 'point',
            'lat' => $lat,
            'lon' => $lng,
        ],
    ];

    $settings['leaflet_map'] = 'OSM Mapnik';

    $map = \Drupal::service('leaflet.service')->leafletMapGetInfo($settings['leaflet_map']);

    $result = \Drupal::service('leaflet.service')->leafletRenderMap($map, $features, $height = '200px');

    $variables['output'] = $result;
}*/