<?php

/**
 * @file
 * Contains parish_school_locator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ResultRow;

/**
 * Implements hook_help().
 */
function parish_school_locator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the parish_school_locator module.
    case 'help.page.parish_school_locator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Find parishes and schools by address, name, and mass time') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function parish_school_locator_theme() {
  return [
    'parish_school_locator' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_uninstall().
 */
function parish_school_locator_uninstall() {
    \Drupal::configFactory()->getEditable('field.field.directory.parishes.field_geolocation')->delete();
    \Drupal::configFactory()->getEditable('field.field.directory.schools.field_geolocation')->delete();
    \Drupal::configFactory()->getEditable('field.storage.directory.field_geolocation')->delete();
}

/**
 * Implements hook_form_alter()
 */
function parish_school_locator_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Parish finder exposed view form
  if (   $form['#id'] == 'views-exposed-form-parish-finder-page-1'
      || $form['#id'] == 'views-exposed-form-parish-finder-page-2'
      || $form['#id'] == 'views-exposed-form-school-finder-page-1'
      || $form['#id'] == 'views-exposed-form-school-finder-page-2') {

    // Hide proximity filter fields
    $form['field_geolocation_proximity']['#type'] = 'hidden';
    $form['field_geolocation_proximity-lat']['#type'] = 'hidden';
    $form['field_geolocation_proximity-lng']['#type'] = 'hidden';

    // Create custom address field for geocoding
    $form['field_geocoded_address']['#type'] = 'textfield';
    $form['field_geocoded_address']['#title'] = t('Nearest to');
    $form['field_geocoded_address']['#attributes']['placeholder'] = t('Enter an address, city & state, or zip code');

    // Create fieldset for Advanced Search filters
    $form['advanced'] = [
        '#type' => 'details',
        '#title' => t('Advanced Search'),
    ];

    // Move deanery and county to Advance Search fieldset
    $form['advanced']['field_county_value'] = $form['field_county_value'];
    $form['advanced']['field_county_value']['#title'] = t('County');
    unset($form['field_county_value']);
    $form['advanced']['field_vicariate_value'] = $form['field_vicariate_value'];
    $form['advanced']['field_vicariate_value']['#title'] = t('Deanery');
    unset($form['field_vicariate_value']);

    // Add a custom form validator for geocoding
    $form['#validate'][] = '_parish_school_locator_validate';
  }
}

/**
 * Custom form validator for exposed filter
 */
function _parish_school_locator_validate(array &$form, FormStateInterface $form_state) {

  // Get address entered by user
  $address = $form_state->getValue('field_geocoded_address');

  // Check if address isn't empty
  if ($address != '') {
    $geolocation = _mapbox_geocode($address); // geocode the address

    // Set latitude
    $form_state->setValue('field_geolocation_proximity-lat', $geolocation[1]);

    // Set longitude
    $form_state->setValue('field_geolocation_proximity-lng', $geolocation[0]);
  }
}

/**
 * Geocode address via Mapbox API
 */
function _mapbox_geocode($address) {

  //Set Mapbox API endpoint
  $endpoint = 'https://api.mapbox.com/geocoding/v5/mapbox.places/';

  // Set Mapbox API
  $config = \Drupal::config('parish_school_locator.mapbox');
  $token = $config->get('mapbox_api_token');

  // Assemble request URL
  $url = $endpoint . $address . '.json?access_token=' . $token;

  // Initialize Guzzle HTTP client
  $client = \Drupal::httpClient();

  try {
    $request = $client->get($url);  // make API call
    $response = $request->getBody();  // get API response
    $output = (array) json_decode($response);  // convert JSON to array
    $output = (array) $output['features'][0]; // get features array
    $output = $output['center']; // get lat/lng center
  }
  catch (RequestException $e) {
    watchdog_exception('parish_school_locator', $e->getMessage());
  }

  return $output;
}

/**
 * Implements hook_views_pre_render().
 */
function parish_school_locator_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'parish_finder')) {
    $view->element['#attached']['library'][] = 'parish_school_locator/parish_school_locator';

    // If no addressed entered, hide proximity field
    if ($view->exposed_widgets['field_geocoded_address']['#value'] == '') {
      unset($view->field['field_geolocation_proximity']);
    }
    if ($view->current_display == 'page_1') {

      // Default to weekend masses if no type or day is selected
      if ($view->exposed_data['field_service_type_value'] == 'All' && $view->exposed_data['field_day_of_week_value'] == 'All') {
        unset($view->field['view_1']);
        unset($view->field['view_2']);
        unset($view->field['view_3']);
        unset($view->field['view_4']);
        unset($view->field['view_5']);
        unset($view->field['view_6']);
      }

      // FILTER BY SELECTED SERVICE TYPE
      // If Weekend selected, only show weekend masses
      if ($view->exposed_data['field_service_type_value'] == 'weekend') {
        unset($view->field['view_1']);
        unset($view->field['view_2']);
        unset($view->field['view_3']);
        unset($view->field['view_4']);
        unset($view->field['view_5']);
        unset($view->field['view_6']);
      }

      // If Weekday selected, only show weekday masses
      if ($view->exposed_data['field_service_type_value'] == 'week_day') {
        unset($view->field['view']);
        unset($view->field['view_2']);
        unset($view->field['view_3']);
        unset($view->field['view_4']);
        unset($view->field['view_5']);
        unset($view->field['view_6']);
      }

      // If Holy Day Vigil selected, only show holy day vigil masses
      if ($view->exposed_data['field_service_type_value'] == 'vigil_holy_days') {
        unset($view->field['view']);
        unset($view->field['view_1']);
        unset($view->field['view_3']);
        unset($view->field['view_4']);
        unset($view->field['view_5']);
        unset($view->field['view_6']);
      }

      // If Holy Days selected, only show holy day masses
      if ($view->exposed_data['field_service_type_value'] == 'holy_days') {
        unset($view->field['view']);
        unset($view->field['view_1']);
        unset($view->field['view_2']);
        unset($view->field['view_4']);
        unset($view->field['view_5']);
        unset($view->field['view_6']);
      }

      // If Confession selected, only show confessions
      if ($view->exposed_data['field_service_type_value'] == 'confession') {
        unset($view->field['view']);
        unset($view->field['view_1']);
        unset($view->field['view_2']);
        unset($view->field['view_3']);
        unset($view->field['view_5']);
        unset($view->field['view_6']);
      }

      // If Adoration selected, only show adorations
      if ($view->exposed_data['field_service_type_value'] == 'adoration') {
        unset($view->field['view']);
        unset($view->field['view_1']);
        unset($view->field['view_2']);
        unset($view->field['view_3']);
        unset($view->field['view_4']);
        unset($view->field['view_6']);
      }

      // If Devotion selected, only show devotions
      if ($view->exposed_data['field_service_type_value'] == 'devotion') {
        unset($view->field['view']);
        unset($view->field['view_1']);
        unset($view->field['view_2']);
        unset($view->field['view_3']);
        unset($view->field['view_4']);
        unset($view->field['view_5']);
      }
    }
  }

  if (isset($view) && ($view->storage->id() == 'school_finder')) {
    $view->element['#attached']['library'][] = 'parish_school_locator/parish_school_locator';
  }

/*  if (isset($view)
      && ( $view->storage->id() == 'parish_adoration_times'
      || $view->storage->id() == 'parish_confession_times'
      || $view->storage->id() == 'parish_devotion_times'
      || $view->storage->id() == 'parish_holy_day_mass_times'
      || $view->storage->id() == 'parish_holy_day_vigil_mass_times'
      || $view->storage->id() == 'parish_week_day_mass_times'
      || $view->storage->id() == 'parish_weekend_mass_times'
      )
  ) {
    // Iterate through each service time
    foreach ($view->result as $key => $value) {
      $day = _find_day_of_week(($view));
      if (isset($day)) {
        dpm($day);
      }
      else {
        dpm($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id());
      }
      _filter_day_of_week($view, $day, $value, $key);
    }
  }*/
}

/**
 * Custom function to filter out services on days that don't match the
 * exposed filter
 *
 * @param $view
 * @param $day
 * @param $value
 */

/*function _filter_day_of_week($view, $day, $value, $key) {
  if (isset($value->_entity->toArray()['field_day_of_week'][0]['value'])
    && $value->_entity->toArray()['field_day_of_week'][0]['value'] != $day
    && $day != 'All'
  ) {

    // If days don't match, don't display the service time
    unset($view->result[$key]);
  }
  else {
    foreach ($view->result as $k => $v) {
      if ($v->mass_times__field_day_of_week_field_day_of_week_value != $day && $day != 'All') {
        unset($view->result[$k]);
      }
    }
  }
}*/

/**
 * Custom function to find day of week exposed value
 *
 * @param $view
 *
 * @return mixed
 */
/*function _find_day_of_week($view) {
  foreach($view->result as $key=>$value) {
    if (isset($view->old_view[0]->exposed_data['field_day_of_week_value'])
        && $view->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->id() == 'parish_finder') {
        $day = $view->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
    elseif (isset($view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'])
      && $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->id() == 'parish_finder') {
      $day = $view->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->old_view[0]->exposed_data['field_day_of_week_value'];
    }
/*    else {
      $view = $view->old_view[0];
      dpm($view->old_view[0]);
      _find_day_of_week($view);
    }*/

/*  }
  if (isset($day)) {
    return $day;
  }
}*/